POST http://localhost:8080/battle HTTP/1.1
content-type: application/json

{
    "Enemy": "A",
    "Player": "TheClip"
}

###
GET http://localhost:8080/battle HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/enemy/A HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/TheClip HTTP/1.1
content-type: application/json

{
}
