POST http://localhost:8080/player HTTP/1.1
content-type: application/json

{
    "nickname": "TheClipBR",
    "life": 10,
    "attack": 2
}

###
GET http://localhost:8080/player HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/player/<uuid> HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/b2f73868-899b-440f-9d0c-9b46c3145f90 HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/player/b2f73868-899b-440f-9d0c-9b46c3145f90 HTTP/1.1
content-type: application/json

{
    "nickname": "TheClipBR",
    "attack": 2,
    "life": 100
}